#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (getTouchLEDValue(touchLED) == 0)
	{}
playSound(soundAirWrench);
while(getBumperValue(bumpSwitch) == 0)
{
	setMotorSpeed(leftMotor, 127);
	setMotorSpeed(rightMotor, 127);
	sleep(2000);
	}
}
