#pragma config(Sensor, port2,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  gray1,          sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port8,  led1,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  distanceSensor, sensorVexIQ_Distance)
#pragma config(Sensor, port11, led2,           sensorVexIQ_LED)
#pragma config(Sensor, port12, gray2,          sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
playSound(sound);

2022-10-09
------------------------------------------------------------------------------------------------*/
int speed;
int returns  = false;
int latency = 1000;
int threshold = 600;
task main()
{

	resetGyro(gyroSensor);
	//While distance sensor is more than 100mm (10cm) away
	while (!returns )
	{
		if(getColorValue(gray1) > 120)
		{
			displayTextLine(1, "Light Area Detected");
			displayTextLine(2, "Proximity Value: %d", getColorValue(gray1));
		}
		else
		{
			displayTextLine(1, "Dark Area Detected");
			displayTextLine(2, "Proximity Value: %d", getColorValue(gray1));
		}

		//if (getDistanceValue(distanceSensor) > 100)
		//{
		//	speed = 100;
		//	setTouchLEDColor(led1, colorGreen);
		//	setTouchLEDColor(led2, colorGreen);
		//	latency = 1000;
		//	} else {
		//	setTouchLEDColor(led1, colorBlueGreen);
		//	setTouchLEDColor(led2, colorBlueGreen);
		//	speed = 10;
		//	latency = 200;
		//}

		//setMotorSpeed(leftMotor, speed);  //Move left motor at 50% speed
		//setMotorSpeed(rightMotor, speed); //Move right motor at 50% speed

	//	sleep(latency);
//		if (getBumperValue(bumpSwitch) == 1) returns = true;
	}

	while(getGyroDegrees(gyroSensor) < 180)
	{
		setTouchLEDColor(led1, colorRed);
		setTouchLEDColor(led2, colorBlue);
	}


}
